CREATE SCHEMA EXERCICIO2;
USE EXERCICIO2;

CREATE TABLE IF NOT EXISTS USUARIOS(
ID_USUARIO INT PRIMARY KEY,
NOME_USUARIO VARCHAR(100) NOT NULL,
SOBRENOME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS GRUPOS(
ID_GRUPO INT PRIMARY KEY,
NOME_GRUPO VARCHAR(100) NOT NULL,
DESCRICAO TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS POSTAGENS(
ID_POST INT PRIMARY KEY,
TEXTO TEXT,
IMAGEM BLOB,
DATA_HORA DATETIME NOT NULL,
USUARIO INT NOT NULL,
POST INT NOT NULL,
FOREIGN KEY(USUARIO) REFERENCES USUARIOS(ID_USUARIO));


CREATE TABLE IF NOT EXISTS COMENTARIOS(
ID_COMENTARIO INT PRIMARY KEY,
TEXTO TEXT NOT NULL,
DATAHORA DATETIME NOT NULL,
USUARIO INT NOT NULL,
POST INT NOT NULL,
FOREIGN KEY(USUARIO) REFERENCES USUARIOS(ID_USUARIO),
FOREIGN KEY(POST) REFERENCES POSTAGENS(ID_POST));

CREATE TABLE IF NOT EXISTS USUARIOS_GRUPOS(
USUARIO INT,
GRUPO INT,
PRIMARY KEY(USUARIO,GRUPO),
FOREIGN KEY(USUARIO) REFERENCES USUARIOS(ID_USUARIO),
FOREIGN KEY(GRUPO) REFERENCES GRUPOS(ID_GRUPO));

CREATE TABLE IF NOT EXISTS SEGUIDORES(
USUARIO INT,
SEGUIDOR INT,
PRIMARY KEY(USUARIO,SEGUIDOR),
FOREIGN KEY(USUARIO) REFERENCES USUARIOS(ID_USUARIO),
FOREIGN KEY(SEGUIDOR) REFERENCES USUARIOS(ID_USUARIO));



ALTER TABLE USUARIOS_GRUPOS
DROP FOREIGN KEY usuarios_grupos_ibfk_2,
ADD CONSTRAINT FK_user_grupo FOREIGN KEY(GRUPO) REFERENCES GRUPOS(ID_GRUPO);








