CREATE DATABASE IF NOT EXISTS BDEX3_REDESOCIAL;
USE BDEX3_REDESOCIAL;

CREATE TABLE IF NOT EXISTS USUARIOS(
ID_USUARIO INT PRIMARY KEY,
NOME_USUARIO VARCHAR(100) NOT NULL,
SOBRENOME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100));

CREATE TABLE IF NOT EXISTS GRUPOS(
ID_GRUPO INT PRIMARY KEY,
NOME_GRUPO VARCHAR(100) NOT NULL,
DESCRICAO TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS POSTAGENS(
ID_POST INT PRIMARY KEY,
TEXTO TEXT,
IMAGEM BLOB,
DATA_HORA DATETIME NOT NULL,
USUARIO INT NOT NULL,
CONSTRAINT USER_POST FOREIGN KEY(USUARIO) REFERENCES USUARIOS(ID_USUARIO));

CREATE TABLE IF NOT EXISTS COMENTARIOS(
ID_COMENTARIO INT PRIMARY KEY,
TEXTO TEXT NOT NULL,
DATAHORA DATETIME NOT NULL,
USUARIO INT NOT NULL,
POST INT NOT NULL,
CONSTRAINT USER_COMM FOREIGN KEY(USUARIO) REFERENCES USUARIOS(ID_USUARIO),
CONSTRAINT POST_COMM FOREIGN KEY(POST) REFERENCES POSTAGENS(ID_POST));

CREATE TABLE IF NOT EXISTS SEGUIDORES_USUARIOS(
USUARIO INT,
SEGUIDOR INT,
PRIMARY KEY(USUARIO,SEGUIDOR),
CONSTRAINT USER1 FOREIGN KEY(USUARIO) REFERENCES USUARIOS(ID_USUARIO),
CONSTRAINT USER2 FOREIGN KEY(SEGUIDOR) REFERENCES USUARIOS(ID_USUARIO));

CREATE TABLE IF NOT EXISTS USUARIOS_GRUPOS(
USUARIO INT,
GRUPO INT,
PRIMARY KEY(USUARIO,GRUPO),
CONSTRAINT USER_GROUP FOREIGN KEY(USUARIO) REFERENCES USUARIOS(ID_USUARIO),
CONSTRAINT GROUP_USER FOREIGN KEY(GRUPO) REFERENCES GRUPOS(ID_GRUPO));

ALTER TABLE USUARIOS
MODIFY COLUMN EMAIL VARCHAR(20) NOT NULL;