CREATE DATABASE IF NOT EXISTS BDEX1_HOSPITAL;
USE BDEX1_HOSPITAL;

CREATE TABLE IF NOT EXISTS PACIENTES(
CPF_PACIENTE VARCHAR(15) PRIMARY KEY,
NOME VARCHAR(45) NOT NULL,
DATA_NASC DATE NOT NULL,
TELEFONE VARCHAR(45) NOT NULL,
EMAIL VARCHAR(45));

CREATE TABLE IF NOT EXISTS DEPARTAMENTOS(
COD_ESPECIALIDADE INT PRIMARY KEY,
NOME_ESPECIALIDADE VARCHAR(45));

CREATE TABLE IF NOT EXISTS MEDICOS(
CRM INT,
UF CHAR(2),
PRIMARY KEY(CRM,UF),
NOME VARCHAR(45) NOT NULL,
EMAIL VARCHAR(45) NOT NULL,
TELEFONE VARCHAR(45) NOT NULL,
DEPTO_COD_ESPEC INT,
CONSTRAINT DEPTO_MED FOREIGN KEY(DEPTO_COD_ESPEC)
REFERENCES DEPARTAMENTOS(COD_ESPECIALIDADE));

CREATE TABLE IF NOT EXISTS CONSULTAS(
ID_CONSULTA INT PRIMARY KEY,
ANAMNESE TEXT,
DATA_CONS DATE NOT NULL,
HORA_CONS TIME NOT NULL,
CRM INT NOT NULL,
UF CHAR(2) NOT NULL,
CPF_PACIENTE VARCHAR(15) NOT NULL,
CONSTRAINT MED_CONS FOREIGN KEY(CRM,UF) 
REFERENCES MEDICOS(CRM,UF),
CONSTRAINT PAC_CONS FOREIGN KEY(CPF_PACIENTE)
REFERENCES PACIENTES(CPF_PACIENTE));
