#Banco de Dados: Exercicio 1
-- 1. Liste todos os participantes e os eventos em que estão inscritos.
SELECT PRT.*, EVT.NOME_EVENTO
FROM PARTICIPANTES AS PRT
JOIN PARTICIPANTES_EVENTOS AS PEV
ON PEV.CPF = PRT.CPF AND PEV.INSCRICAO = PRT.NUM_INSCRICAO
JOIN EVENTOS AS EVT ON EVT.LOCAL_EVENTO = PEV.EVENTO;

-- 2. Exiba a lista de eventos com o local em que serão realizados.
SELECT EVT.NOME_EVENTO,LCL.NOME
FROM EVENTOS AS EVT
JOIN LOCAIS AS LCL ON LCL.ID_LOCAL = EVT.LOCAL_EVENTO;

-- 3. Liste todos os participantes, as atividades nas quais estão inscritos e os eventos correspondentes.
SELECT PRT.NOME AS 'NOME DO PARTICIPANTE', 
ATV.NOME_ATV AS 'ATIVIDADE INSCRITA', 
EVT.NOME_EVENTO AS 'EVENTO DA ATIVIDADE'
FROM PARTICIPANTES AS PRT
JOIN PARTICIPANTES_ATIVIDADES AS PA
ON PRT.NUM_INSCRICAO = PA.INSCRICAO AND PRT.CPF = PA.CPF
JOIN ATIVIDADES AS ATV
ON ATV.ID_ATIVIDADE = PA.ATIVIDADE
JOIN EVENTOS AS EVT
ON EVT.ID_EVENTO = ATV.EVENTO_ATV;

-- 4. Encontre os participantes que estão inscritos em atividades de um evento específico, filtrando por evento.
SELECT GROUP_CONCAT(PRT.NOME) AS 'NOME DO PARTICIPANTE', 
ATV.NOME_ATV AS 'ATIVIDADE INSCRITA'
FROM PARTICIPANTES AS PRT
JOIN PARTICIPANTES_ATIVIDADES AS PA
ON PRT.NUM_INSCRICAO = PA.INSCRICAO AND PRT.CPF = PA.CPF
JOIN ATIVIDADES AS ATV
ON ATV.ID_ATIVIDADE = PA.ATIVIDADE
JOIN EVENTOS AS EVT
ON EVT.ID_EVENTO = ATV.EVENTO_ATV
WHERE EVT.NOME_EVENTO = 'FEIRA DE EMPREENDEDORISMO'
GROUP BY ATV.NOME_ATV;

#OU

SELECT PRT.NOME AS 'NOME DO PARTICIPANTE'
FROM PARTICIPANTES AS PRT
JOIN PARTICIPANTES_ATIVIDADES AS PA
ON PRT.NUM_INSCRICAO = PA.INSCRICAO AND PRT.CPF = PA.CPF
JOIN ATIVIDADES AS ATV
ON ATV.ID_ATIVIDADE = PA.ATIVIDADE
JOIN EVENTOS AS EVT
ON EVT.ID_EVENTO = ATV.EVENTO_ATV
WHERE EVT.NOME_EVENTO = 'FEIRA DE EMPREENDEDORISMO';


-- 5. Exiba a quantidade de participantes inscritos em cada evento.
SELECT EVT.NOME_EVENTO, COUNT(*) AS QUANTIDADE
FROM PARTICIPANTES AS PRT
JOIN PARTICIPANTES_EVENTOS AS PE
ON PE.INSCRICAO = PRT.NUM_INSCRICAO AND PE.CPF = PRT.CPF
JOIN EVENTOS AS EVT
ON PE.EVENTO = EVT.ID_EVENTO
GROUP BY EVT.NOME_EVENTO;

-- 6. Liste todas as atividades e os participantes inscritos em cada uma.
SELECT ATV.NOME_ATV, GROUP_CONCAT(PRT.NOME) AS INSCRITOS
FROM PARTICIPANTES AS PRT
JOIN PARTICIPANTES_ATIVIDADES AS PA
ON PRT.NUM_INSCRICAO = PA.INSCRICAO AND PRT.CPF = PA.CPF
JOIN ATIVIDADES AS ATV
ON ATV.ID_ATIVIDADE = PA.ATIVIDADE
GROUP BY ATV.NOME_ATV;

-- 7. Exiba a lista de eventos que estão programados para um determinado local.
#VERSAO NUTELLA
SELECT LCL.NOME, EVT.NOME_EVENTO
FROM EVENTOS AS EVT
JOIN LOCAIS AS LCL ON EVT.LOCAL_EVENTO = LCL.ID_LOCAL;

#VERSAO RAIZ
SELECT LCL.NOME, GROUP_CONCAT(EVT.NOME_EVENTO) AS EVENTOS
FROM EVENTOS AS EVT
JOIN LOCAIS AS LCL ON EVT.LOCAL_EVENTO = LCL.ID_LOCAL
GROUP BY LCL.NOME;

-- 8. Encontre a lista de todos os locais e o número de eventos realizados em cada um deles.
SELECT LCL.NOME, COUNT(*) AS EVENTOS
FROM EVENTOS AS EVT
JOIN LOCAIS LCL ON EVT.LOCAL_EVENTO = LCL.ID_LOCAL
GROUP BY LCL.NOME;

-- 9. Liste o nome dos participantes, as atividades em que estão inscritos e a data e hora dessas atividades.
SELECT ATV.NOME_ATV, ATV.DATA_ATV, ATV.HORA_ATV, PRT.NOME
FROM ATIVIDADES AS ATV
JOIN PARTICIPANTES_ATIVIDADES AS PA
ON PA.ATIVIDADE = ATV.ID_ATIVIDADE
JOIN PARTICIPANTES AS PRT
ON PRT.CPF = PA.CPF AND PRT.NUM_INSCRICAO = PA.INSCRICAO;
 #OU
SELECT ATV.NOME_ATV, ATV.DATA_ATV, ATV.HORA_ATV, GROUP_CONCAT(PRT.NOME) AS PARTICIPANTES
FROM ATIVIDADES AS ATV
JOIN PARTICIPANTES_ATIVIDADES AS PA
ON PA.ATIVIDADE = ATV.ID_ATIVIDADE
JOIN PARTICIPANTES AS PRT
ON PRT.CPF = PA.CPF AND PRT.NUM_INSCRICAO = PA.INSCRICAO
GROUP BY ATV.NOME_ATV, ATV.DATA_ATV, ATV.HORA_ATV;

-- 10. Mostre o nome dos participantes e a entidade organizadora dos eventos em que estão inscritos.
SELECT EVT.ENTIDADE_EVENTO, GROUP_CONCAT(PRT.NOME) AS PARTICIPANTES
FROM PARTICIPANTES AS PRT
JOIN PARTICIPANTES_EVENTOS AS PE
ON PE.INSCRICAO = PRT.NUM_INSCRICAO AND PE.CPF = PRT.CPF
JOIN EVENTOS AS EVT
ON PE.EVENTO = EVT.ID_EVENTO
GROUP BY EVT.ENTIDADE_EVENTO;
