#BDEX1
use bdex1_hospital;

#1 - Quais são os pacientes ordenados por idade?
SELECT * FROM PACIENTES
ORDER BY timestampdiff(YEAR,DATA_NASC,CURDATE());
#OU, SE QUISER EXIBIR A IDADE
SELECT *, timestampdiff(YEAR,DATA_NASC,CURDATE()) AS IDADE
FROM PACIENTES
ORDER BY IDADE;

#2 - Quantos pacientes existem em cada departamento?
SELECT D.NOME_ESPECIALIDADE, COUNT(*) AS QUANTIDADE
FROM PACIENTES AS P
JOIN CONSULTAS AS C ON C.CPF_PACIENTE = P.CPF_PACIENTE
JOIN MEDICOS AS M ON M.CRM = C.CRM AND C.UF = M.UF
JOIN DEPARTAMENTOS AS D ON D.COD_ESPECIALIDADE = M.DEPTO_COD_ESPEC
GROUP BY D.NOME_ESPECIALIDADE;
#ORDER BY QUANTIDADE DESC
#LIMIT 1;

#3 - Qual é a média de idade dos pacientes por departamento?
SELECT D.NOME_ESPECIALIDADE, 
ROUND(AVG(TIMESTAMPDIFF(YEAR,DATA_NASC,CURDATE()))) AS IDADE
FROM PACIENTES P
JOIN CONSULTAS C ON C.CPF_PACIENTE = P.CPF_PACIENTE
JOIN MEDICOS M ON M.CRM = C.CRM AND C.UF = M.UF
JOIN DEPARTAMENTOS D ON D.COD_ESPECIALIDADE = M.DEPTO_COD_ESPEC
GROUP BY D.NOME_ESPECIALIDADE;

#BDEX2
use bdex2_passagens_aereas;
#1 - Quais são os voos ordenados por data e hora de partida?
SELECT * FROM VOOS
ORDER BY DATA_PART,HORA_PART;
#OU MAIS COMPLEXO QUE ISSO
SELECT V.DATA_PART DATA_VOO, V.HORA_PART HORA_VOO, 
PARTIDA.CIDADE PARTIDA, CHEGADA.CIDADE CHEGADA 
FROM VOOS V
JOIN AEROPORTOS PARTIDA ON PARTIDA.ID_AEROPORTO = V.AERO_PART 
JOIN AEROPORTOS CHEGADA ON CHEGADA.ID_AEROPORTO = V.AERO_CHEG
ORDER BY DATA_VOO,HORA_VOO;

#2 - Quantos passageiros estão reservados para cada voo?
SELECT V.ID_VOO, COUNT(*) AS QUANTIDADE 
FROM PASSAGEIROS_RESERVAS PR
JOIN RESERVAS R ON R.ID_RESERVA = PR.ID_RESERVA
JOIN VOOS_RESERVAS VR ON VR.ID_RESERVA = R.ID_RESERVA
JOIN VOOS V ON V.ID_VOO = VR.ID_VOO
GROUP BY V.ID_VOO;

#3 - Qual é a média de passageiros reservados por voo?
SELECT AVG(PASSAGEIROS) MEDIA_PASSAGEIROS
FROM (
SELECT COUNT(*) PASSAGEIROS 
FROM VOOS_RESERVAS
GROUP BY ID_VOO
) PASSAGENS;

#BDEX3
USE BDEX3_REDESOCIAL;
#1 - Quais são as postagens ordenadas por data e hora de criação?
# SHOW COLUMNS FROM COMENTARIOS;
SELECT * FROM POSTAGENS
ORDER BY DATA_HORA DESC;
#2 - Quantos comentários cada postagem possui?
SELECT POST,COUNT(*) FROM COMENTARIOS
GROUP BY POST;

#3 - Qual é o número médio de comentários por postagem?
SELECT AVG(COMENTARIO) 
FROM( 	SELECT COUNT(*) COMENTARIO 
		FROM COMENTARIOS
		GROUP BY POST) COMMENTS;

#BDEX4
USE BDEX4_ESTOQUE;
#1 - Quais são os produtos ordenados por preço?
SELECT * FROM PRODUTOS
ORDER BY PRECO;

#2 - Quantos produtos existem em cada armazém?
SELECT ARMAZEM, SUM(QUANTIDADE) PRODUTOS
FROM PRODUTOS_ARMAZENS
GROUP BY ARMAZEM;

#3 - Qual é o valor total de estoque por fornecedor?
SELECT F.CNPJ, F.NOME, SUM(P.PRECO) VALOR_TOTAL 
FROM FORNECEDORES F
JOIN PRODUTOS_FORNECEDORES PF 
ON PF.FORNECEDOR = F.ID_FORNECEDOR
JOIN PRODUTOS P
ON PF.PRODUTO = P.ID_PRODUTO
GROUP BY F.CNPJ,F.NOME;

#BDEX5
USE BDEX5_EVENTOS;
#1 - Quais são os eventos ordenados por data?
SELECT * FROM EVENTOS
ORDER BY DATA_EVENTO DESC;

#2 - Quantas atividades cada evento possui?
SELECT E.NOME_EVENTO, COUNT(*) QUANTIDADE 
FROM ATIVIDADES A
JOIN EVENTOS E ON E.ID_EVENTO = A.EVENTO_ATV
GROUP BY E.NOME_EVENTO;

#3 - Qual é o número médio de participantes por atividade?
SELECT AVG(PARTICIPANTES)
FROM(
	SELECT COUNT(*) AS PARTICIPANTES 
    FROM ATIVIDADES
    GROUP BY ID_ATIVIDADE) AS BASE;

#BDEX6
USE BDEX6_CINEMA;
#1 - Quais são os filmes ordenados por nome?
SELECT * FROM FILMES
ORDER BY NOME_FILME;
#2 - Quantas sessões cada filme possui?
SELECT F.NOME_FILME, COUNT(*) AS QUANTIDADE 
FROM SESSOES S
JOIN FILMES F ON F.ID_FILME = S.FILME
GROUP BY F.NOME_FILME;

#3 - Qual é o horário mais popular para as sessões de cinema?
SELECT HORA_ING AS HORARIO_POPULAR
FROM INGRESSOS
GROUP BY HORA_ING
ORDER BY COUNT(*) DESC
LIMIT 1;

#CONFERINDO...
SELECT HORA_ING, COUNT(*)
FROM INGRESSOS
GROUP BY HORA_ING
ORDER BY COUNT(*) DESC;

#BDEX7
USE BDEX7_TRANSACOESBANCARIAS;
#1 - Quais são as transações bancárias ordenadas por valor?
SELECT * 
FROM TRANSACOES
ORDER BY VALOR;

#2 - Quantas transações ocorreram em cada conta?
SELECT CONTA, COUNT(*) NUM_TRANSACOES 
FROM TRANSACOES
GROUP BY CONTA;

#3 - Qual é o valor médio das transações por usuário?
SELECT * FROM TRANSACOES;
SELECT ROUND(AVG(VALOR_USUARIO),2) AS VALOR_MEDIO
FROM(
	SELECT SUM(VALOR) VALOR_USUARIO 
    FROM TRANSACOES
    GROUP BY USUARIO) AS TRANS_USER;