-- Exclusão na tabela ESPECTADORES
DELETE FROM ESPECTADORES
WHERE ID_ESPEC = 2;

-- Exclusão na tabela SALAS
DELETE FROM SALAS
WHERE ID_SALA = 2;

-- Exclusão na tabela FILMES
DELETE FROM FILMES
WHERE ID_FILME = 2;

-- Exclusão na tabela SESSOES
DELETE FROM SESSOES
WHERE ID_SESSAO = 2;

-- Exclusão na tabela INGRESSOS
DELETE FROM INGRESSOS
WHERE ID_INGRESSO = 2;
