CREATE SCHEMA IF NOT EXISTS BDEX5_EVENTOS;
USE BDEX5_EVENTOS;

CREATE TABLE IF NOT EXISTS PARTICIPANTES(
NUM_INSCRICAO INT,
CPF VARCHAR(20),
NOME VARCHAR(100) NOT NULL,
DATA_NASC DATE NOT NULL,
EMPRESA VARCHAR(100),
PRIMARY KEY(NUM_INSCRICAO,CPF));

CREATE TABLE IF NOT EXISTS LOCAIS(
ID_LOCAL INT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
LOG_LOCAL VARCHAR(100) NOT NULL,
NUMLOG_LOCAL INT,
BAIRRO_LOCAL VARCHAR(100) NOT NULL,
CIDADE VARCHAR(100) NOT NULL,
UF CHAR(2) NOT NULL,
CEP VARCHAR(20) NOT NULL,
CAPACIDADE INT NOT NULL);

CREATE TABLE IF NOT EXISTS EVENTOS(
ID_EVENTO INT PRIMARY KEY,
NOME_EVENTO VARCHAR(100) NOT NULL,
DATA_EVENTO DATE NOT NULL,
ENTIDADE_EVENTO VARCHAR(100) NOT NULL,
LOCAL_EVENTO INT,
CONSTRAINT LCL_EVT FOREIGN KEY(LOCAL_EVENTO) REFERENCES LOCAIS(ID_LOCAL));

CREATE TABLE IF NOT EXISTS ATIVIDADES(
ID_ATIVIDADE INT PRIMARY KEY,
NOME_ATV VARCHAR(100) NOT NULL,
DATA_ATV DATE NOT NULL,
HORA_ATV TIME NOT NULL,
EVENTO_ATV INT NOT NULL,
CONSTRAINT EVT_ATV FOREIGN KEY(EVENTO_ATV)REFERENCES EVENTOS(ID_EVENTO));

CREATE TABLE IF NOT EXISTS PARTICIPANTE_ATIVIDADE(
INSCRICAO INT,
CPF VARCHAR(20),
ATIVIDADE INT,
PRIMARY KEY(INSCRICAO, CPF, ATIVIDADE),
CONSTRAINT PA1 FOREIGN KEY(INSCRICAO,CPF) REFERENCES PARTICIPANTES(NUM_INSCRICAO,CPF),
CONSTRAINT PA2 FOREIGN KEY(ATIVIDADE) REFERENCES ATIVIDADES(ID_ATIVIDADE));

CREATE TABLE IF NOT EXISTS PARTICIPANTE_EVENTO(
INSCRICAO INT,
CPF VARCHAR(20),
EVENTO INT,
PRIMARY KEY(INSCRICAO, CPF, EVENTO),
CONSTRAINT PE1 FOREIGN KEY(INSCRICAO,CPF) REFERENCES PARTICIPANTES(NUM_INSCRICAO,CPF),
CONSTRAINT PE2 FOREIGN KEY(EVENTO) REFERENCES EVENTOS(ID_EVENTO));
