CREATE DATABASE PROVA_CC1M;

USE PROVA_CC1M;

CREATE TABLE IF NOT EXISTS CARROS(
CAR_REGISTRO INT PRIMARY KEY,
CAR_MARCA VARCHAR(20) NOT NULL);

CREATE TABLE IF NOT EXISTS CLIENTES(
CLI_NUMERO INT PRIMARY KEY,
CLI_NOME VARCHAR(50) NOT NULL,
CLI_RUA VARCHAR(100) NOT NULL,
CLI_NUMRUA INT,
CLI_BAIRRO VARCHAR(50) NOT NULL,
CLI_CIDADE VARCHAR(50) NOT NULL,
CLI_ESTADO VARCHAR(30) NOT NULL,
CLI_CEP VARCHAR(10) NOT NULL);

CREATE TABLE IF NOT EXISTS ACIDENTES(
ACID_DATA DATE NOT NULL,
ACID_HORA TIME NOT NULL,
ACID_LOCAL TEXT NOT NULL,
ACID_CARRO INT PRIMARY KEY,
CONSTRAINT FK_CARRO FOREIGN KEY(ACID_CARRO) REFERENCES CARROS(CAR_REGISTRO));

CREATE TABLE IF NOT EXISTS CARROS_CLIENTES(
CR_CARRO INT,
CR_DONO INT,
PRIMARY KEY(CR_DONO,CR_CARRO),
CONSTRAINT CC_FK_CARRO FOREIGN KEY(CR_CARRO) REFERENCES CARROS(CAR_REGISTRO),
CONSTRAINT CC_FK_CLIENTE FOREIGN KEY(CR_DONO) REFERENCES CLIENTES(CLI_NUMERO));

CREATE TABLE IF NOT EXISTS APOLICES(
APOL_NUM INT PRIMARY KEY,
APOL_VALOR DECIMAL(10,2) NOT NULL,
APOL_CLIENTE INT NOT NULL,
APOL_CARRO INT NOT NULL,
CONSTRAINT APOL_FK_CLIENTECARRO FOREIGN KEY(APOL_CLIENTE,APOL_CARRO) REFERENCES CARROS_CLIENTES(CR_DONO,CR_CARRO));
