#Usando a base de dados BDEX3_REDESOCIAL, responda:
USE BDEX3_REDESOCIAL;

#1. Exibir todas as informações da tabela `USUARIOS`.
#SHOW TABLES FROM BDEX3_REDESOCIAL;
SELECT *
FROM USUARIOS;

#2. Mostrar os nomes, sobrenomes e e-mails de todos os usuários.
#DESC USUARIOS;
SELECT CONCAT_WS(' ',NOME_USUARIO, SOBRENOME) AS NOME_COMPLETO, EMAIL
FROM USUARIOS;

#3. Listar os nomes e descrições de todos os grupos.
#DESC GRUPOS;
SELECT NOME_GRUPO, DESCRICAO
FROM GRUPOS;

#4. Exibir os detalhes das postagens: ID da postagem, texto, data e hora, e o nome do usuário que postou.
#DESC POSTAGENS;
#DESC USUARIOS;
SELECT
POST.ID_POST, POST.TEXTO, POST.DATA_HORA, 
CONCAT_WS(' ',USER.NOME_USUARIO,USER.SOBRENOME) AS USUARIO
FROM POSTAGENS AS POST
JOIN USUARIOS AS USER
ON POST.USUARIO = USER.ID_USUARIO;

#5. Listar o nome dos usuários e a quantidade de postagens que cada um fez.
SELECT
CONCAT_WS(' ',USER.NOME_USUARIO,USER.SOBRENOME) AS USUARIO,
COUNT(POST.ID_POST) AS POSTS 
FROM POSTAGENS AS POST RIGHT JOIN USUARIOS AS USER
ON POST.USUARIO = USER.ID_USUARIO
GROUP BY USUARIO;

#6. Mostrar os nomes dos usuários que fizeram comentários em 2024.
DESC COMENTARIOS;
SELECT
CONCAT_WS(' ',USER.NOME_USUARIO,USER.SOBRENOME) AS USUARIO,
COUNT(COM.ID_COMENTARIO) AS QTDE_COMENTARIOS 
FROM COMENTARIOS AS COM RIGHT JOIN USUARIOS AS USER
ON COM.USUARIO = USER.ID_USUARIO
WHERE YEAR(COM.DATAHORA) = 2024
GROUP BY USUARIO;#OU USER.NOME_USUARIO,USER.SOBRENOME;

#7. Listar todos os grupos, ordenados pelo nome do grupo de A a Z.
DESC GRUPOS;
SELECT NOME_GRUPO
FROM GRUPOS
ORDER BY NOME_GRUPO;

#8. Mostrar os nomes dos grupos que têm a palavra "Tecnologia" na descrição.
SELECT NOME_GRUPO
FROM GRUPOS
WHERE DESCRICAO LIKE '%TECNOLOGIA%';

#9. Exibir os detalhes dos comentários: ID do comentário, texto, data e hora, nome do usuário que comentou e ID da postagem comentada.
SELECT COMM.ID_COMENTARIO,COMM.TEXTO,COMM.DATAHORA, #TABELA COMENTARIOS
USER.NOME_USUARIO, #TABELA USUARIOS
POST.ID_POST #TABELA POSTAGENS
FROM COMENTARIOS COMM
JOIN USUARIOS USER #INNER JOIN
ON USER.ID_USUARIO = COMM.USUARIO
JOIN POSTAGENS POST #INNER JOIN
ON COMM.POST = POST.ID_POST;

#10. Para cada postagem, mostrar o ID da postagem e a quantidade de comentários.
SELECT POST.ID_POST,COUNT(COMM.ID_COMENTARIO) AS QUANT_COMENTARIOS
FROM COMENTARIOS COMM
RIGHT JOIN POSTAGENS POST #INNER JOIN
ON COMM.POST = POST.ID_POST
GROUP BY POST.ID_POST;

#11. Contar quantos seguidores cada usuário possui.
SELECT CONCAT_WS(' ',USER.NOME_USUARIO,USER.SOBRENOME) AS USUARIO,
COUNT(SEG.SEGUIDOR) AS SEGUIDORES
FROM USUARIOS USER
LEFT JOIN SEGUIDORES_USUARIOS SEG
ON USER.ID_USUARIO = SEG.USUARIO
GROUP BY USUARIO;

#12. Listar os nomes dos usuários que pertencem ao grupo "Desenvolvimento".
#DESC USUARIOS;
#DESC USUARIOS_GRUPOS;
#DESC GRUPOS;
SELECT CONCAT_WS(' ',USER.NOME_USUARIO,USER.SOBRENOME) AS USUARIO
FROM USUARIOS USER
INNER JOIN USUARIOS_GRUPOS UG
ON USER.ID_USUARIO = UG.USUARIO
INNER JOIN GRUPOS GRU
ON GRU.ID_GRUPO = UG.GRUPO
WHERE GRU.NOME_GRUPO LIKE '%DESENVOLVIMENTO%';

#13. Mostrar o nome dos usuários e a data e hora da última postagem que eles fizeram.
SELECT CONCAT_WS(' ',USER.NOME_USUARIO,USER.SOBRENOME) AS USUARIO,
MAX(POST.DATA_HORA) AS ULTIMO_POST
FROM USUARIOS USER
LEFT JOIN POSTAGENS POST
ON USER.ID_USUARIO = POST.USUARIO
GROUP BY USUARIO;

#14. Contar quantas postagens cada usuário fez.
SELECT CONCAT_WS(' ',USER.NOME_USUARIO,USER.SOBRENOME) AS USUARIO,
COUNT(POST.ID_POST) AS QTDE_POSTS
FROM USUARIOS USER
LEFT JOIN POSTAGENS POST
ON USER.ID_USUARIO = POST.USUARIO
GROUP BY USUARIO;

#15. Para cada grupo, exibir o nome do grupo e a quantidade de usuários que pertencem a ele.
DESC GRUPOS;
SELECT GRU.NOME_GRUPO AS GRUPO,
COUNT(USER.ID_USUARIO) AS QTDE_USUARIOS
FROM USUARIOS USER
RIGHT JOIN USUARIOS_GRUPOS UG
ON USER.ID_USUARIO = UG.USUARIO
RIGHT JOIN GRUPOS GRU
ON GRU.ID_GRUPO = UG.GRUPO
GROUP BY GRUPO;
