CREATE SCHEMA IF NOT EXISTS BDEX4_ESTOQUE;
USE BDEX4_ESTOQUE;

CREATE TABLE IF NOT EXISTS PRODUTOS(
ID_PRODUTO INT PRIMARY KEY,
NOME_PRO VARCHAR(100) NOT NULL,
DESCRICAO TEXT NOT NULL,
PRECO DECIMAL(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDORES(
ID_FORNECEDOR INT PRIMARY KEY,
CNPJ VARCHAR(20) NOT NULL,
NOME_FOR VARCHAR(100) NOT NULL,
CIDADE VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ARMAZENS(
ID_ARMAZEM INT PRIMARY KEY,
NOME_ARMAZEM VARCHAR(100) NOT NULL,
LOG_ARMAZEM VARCHAR(100) NOT NULL,
NUMLOG_ARMAZEM INT,
BAIRRO_ARMAZEM VARCHAR(100) NOT NULL,
CIDADE_ARMAZEM VARCHAR(100) NOT NULL,
UF_ARMAZEM CHAR(2) NOT NULL);

CREATE TABLE IF NOT EXISTS PRODUTOS_FORNECEDORES(
PRODUTO INT,
FORNECEDOR INT,
PRIMARY KEY(PRODUTO,FORNECEDOR),
CONSTRAINT PROD_FORN FOREIGN KEY(PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO),
CONSTRAINT FORN_PROD FOREIGN KEY(FORNECEDOR) REFERENCES FORNECEDORES(ID_FORNECEDOR)
);

CREATE TABLE IF NOT EXISTS PEDIDOS_COMPRA(
ID_PEDIDO INT NOT NULL,
DATA_PEDIDO DATE NOT NULL,
HORA_PEDIDO TIME NOT NULL,
FORNECEDOR INT NOT NULL,
PRODUTO INT NOT NULL,
QUANTIDADE INT NOT NULL,
PRIMARY KEY(ID_PEDIDO,FORNECEDOR,PRODUTO),
CONSTRAINT FORNECEDOR_PEDIDO FOREIGN KEY(FORNECEDOR) REFERENCES FORNECEDORES(ID_FORNECEDOR),
CONSTRAINT PRODUTO_PEDIDO FOREIGN KEY(PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);

CREATE TABLE IF NOT EXISTS PRODUTOS_ARMAZENS(
PRODUTO INT NOT NULL,
ARMAZEM INT NOT NULL,
QUANTIDADE INT NOT NULL,
PRIMARY KEY(PRODUTO, ARMAZEM),
CONSTRAINT PRODUTO_ARMAZEM FOREIGN KEY(PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO),
CONSTRAINT ARMAZEM_PRODUTO FOREIGN KEY(ARMAZEM) REFERENCES ARMAZENS(ID_ARMAZEM)
);
