CREATE DATABASE IF NOT EXISTS BDEX7_TRANSACOESBANCARIAS;
USE BDEX7_TRANSACOESBANCARIAS;

CREATE TABLE IF NOT EXISTS USUARIOS(
ID_USER INT PRIMARY KEY,
NOME_USER VARCHAR(100) NOT NULL,
CPF_USER VARCHAR(20) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
TELEFONE VARCHAR(20) NOT NULL,
DATA_NASC DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS CONTAS(
AGENCIA VARCHAR(10),
CONTA VARCHAR(15),
COD_BANCO INT,
PRIMARY KEY(AGENCIA,CONTA,COD_BANCO),
NOME_BNC VARCHAR(100) NOT NULL,
END_BNC VARCHAR(100) NOT NULL,
NUMEND_BNC INT,
BAIRRO_BNC VARCHAR(100) NOT NULL,
CIDADE_BNC VARCHAR(100) NOT NULL,
UF_BNC CHAR(2) NOT NULL,
TELEFONE_BNC VARCHAR(20) NOT NULL,
EMAIL_BNC VARCHAR(50) NOT NULL,
USUARIO INT NOT NULL
);

CREATE TABLE IF NOT EXISTS TRANSACOES(
ID_TRANS INT PRIMARY KEY,
VALOR DECIMAL(10,2) NOT NULL,
NATUREZA ENUM("CREDITO","DEBITO") NOT NULL,
USUARIO INT NOT NULL,
AGENCIA VARCHAR(10) NOT NULL,
CONTA VARCHAR(15) NOT NULL,
COD_BANCO INT NOT NULL,
CONSTRAINT USER_TRANS FOREIGN KEY(USUARIO) REFERENCES USUARIOS(ID_USER),
CONSTRAINT CONTA_TRANS FOREIGN KEY(AGENCIA, CONTA, COD_BANCO) 
REFERENCES CONTAS(AGENCIA,CONTA,COD_BANCO));

CREATE TABLE IF NOT EXISTS SALDOS(
AGENCIA VARCHAR(10),
CONTA VARCHAR(15),
COD_BANCO INT,
DATA_SALDO DATE NOT NULL,
HORA_SALDO TIME NOT NULL,
VALOR_SALDO DECIMAL(10,2) NOT NULL,
PRIMARY KEY(AGENCIA,CONTA,COD_BANCO,DATA_SALDO,HORA_SALDO),
CONSTRAINT CONTA_SALDO FOREIGN KEY(AGENCIA, CONTA, COD_BANCO) 
REFERENCES CONTAS(AGENCIA,CONTA,COD_BANCO));
