CREATE DATABASE IF NOT EXISTS BDEX6_CINEMA;
USE BDEX6_CINEMA;

CREATE TABLE IF NOT EXISTS ESPECTADORES(
ID_ESPEC INT PRIMARY KEY,
TEL_ESPEC VARCHAR(20),
EMAIL_ESPEC VARCHAR(50) NOT NULL,
NOME_ESPEC VARCHAR(100) NOT NULL,
DATA_NASC DATE NOT NULL);

CREATE TABLE IF NOT EXISTS SALAS(
ID_SALA INT PRIMARY KEY,
NOME VARCHAR(50) NOT NULL,
CAPACIDADE INT NOT NULL
);
CREATE TABLE IF NOT EXISTS FILMES(
ID_FILME INT PRIMARY KEY,
NOME_FILME VARCHAR(100) NOT NULL,
DISTRIBUIDOR_FILME VARCHAR(100) NOT NULL,
TEMPO_FILME INT NOT NULL,
DIRETOR VARCHAR(50) NOT NULL);

CREATE TABLE IF NOT EXISTS SESSOES(
ID_SESSAO INT PRIMARY KEY,
FILME INT NOT NULL,
SALA INT NOT NULL,
CONSTRAINT FILME_SESSAO FOREIGN KEY(FILME) REFERENCES FILMES(ID_FILME),
CONSTRAINT SALA_SESSAO FOREIGN KEY(SALA) REFERENCES SALAS(ID_SALA));

CREATE TABLE IF NOT EXISTS INGRESSOS(
ID_INGRESSO INT PRIMARY KEY,
DATA_ING DATE NOT NULL,
HORA_ING TIME NOT NULL,
SESSAO INT NOT NULL,
CONSTRAINT SESSAO_INGRE FOREIGN KEY(SESSAO) REFERENCES SESSOES(ID_SESSAO),
ESPECTADOR INT NOT NULL,
CONSTRAINT ESPEC_INGRE FOREIGN KEY(ESPECTADOR) REFERENCES ESPECTADORES(ID_ESPEC));

