CREATE DATABASE IF NOT EXISTS BDEX2_PASSAGENS_AEREAS;
USE BDEX2_PASSAGENS_AEREAS;

CREATE TABLE IF NOT EXISTS PASSAGEIROS(
COD_PASSAGEIRO INT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
SOBRENOME VARCHAR(100) NOT NULL,
DATA_NASC DATE NOT NULL,
NACIONALIDADE VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS AEROPORTOS(
ID_AEROPORTO INT PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
CIDADE VARCHAR(100) NOT NULL,
ESTADO VARCHAR(100) NOT NULL,
PAIS VARCHAR(100) NOT NULL,
LATITUDE VARCHAR(50) NOT NULL,
LONGITUDE VARCHAR(50) NOT NULL,
TAMANHO_PISTA DECIMAL(20,1) NOT NULL
);

CREATE TABLE IF NOT EXISTS CIA_AEREAS(
ID_CIA INT PRIMARY KEY,
CNPJ VARCHAR(20) NOT NULL,
NOME_FANTASIA VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS RESERVAS(
ID_RESERVA INT PRIMARY KEY,
DATA_RESERVA DATE NOT NULL,
FORMA_PGTO ENUM("DINHEIRO","PIX","DEBITO","CREDITO") NOT NULL,
VALOR_RESERVA DECIMAL(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS AERONAVES(
PFX_AERO VARCHAR(20) PRIMARY KEY,
MODELO VARCHAR(50) NOT NULL,
ANO_FABR YEAR NOT NULL,
FABRICANTE VARCHAR(50) NOT NULL,
POLTRONAS INT NOT NULL,
CIA_AEREA INT NOT NULL,
CONSTRAINT CIA_AERO FOREIGN KEY(CIA_AEREA) REFERENCES CIA_AEREAS(ID_CIA));

CREATE TABLE IF NOT EXISTS VOOS(
ID_VOO INT,
ASSENTO VARCHAR(10),
AERO_PART INT NOT NULL,
DATA_PART DATE NOT NULL,
HORA_PART TIME NOT NULL,
AERO_CHEG INT NOT NULL,
DATA_CHEG DATE NOT NULL,
HORA_CHEG TIME NOT NULL,
AERONAVE VARCHAR(20) NOT NULL,
CIA_AEREA INT NOT NULL,
PRIMARY KEY(ID_VOO,ASSENTO),
CONSTRAINT AEROP_VOO1 FOREIGN KEY(AERO_PART) REFERENCES AEROPORTOS(ID_AEROPORTO),
CONSTRAINT AEROP_VOO2 FOREIGN KEY(AERO_CHEG) REFERENCES AEROPORTOS(ID_AEROPORTO),  
CONSTRAINT AERON_VOO FOREIGN KEY(AERONAVE) REFERENCES AERONAVES(PFX_AERO),
CONSTRAINT CIA_VOO FOREIGN KEY(CIA_AEREA) REFERENCES CIA_AEREAS(ID_CIA));

CREATE TABLE IF NOT EXISTS VOOS_RESERVAS(
ID_VOO INT,
ASSENTO VARCHAR(10),
ID_RESERVA INT,
PRIMARY KEY(ID_VOO,ASSENTO,ID_RESERVA),
CONSTRAINT VR1 FOREIGN KEY(ID_VOO,ASSENTO) REFERENCES VOOS(ID_VOO,ASSENTO),
CONSTRAINT VR2 FOREIGN KEY(ID_RESERVA) REFERENCES RESERVAS(ID_RESERVA)
);

CREATE TABLE IF NOT EXISTS PASSAGEIROS_RESERVAS(
PASSAGEIRO INT,
ID_RESERVA INT,
PRIMARY KEY(PASSAGEIRO,ID_RESERVA),
CONSTRAINT PR1 FOREIGN KEY(PASSAGEIRO) REFERENCES PASSAGEIROS(COD_PASSAGEIRO),
CONSTRAINT PR2 FOREIGN KEY(ID_RESERVA) REFERENCES RESERVAS(ID_RESERVA));