CREATE SCHEMA EXERCICIO1_DDL;
USE EXERCICIO1_DDL;

CREATE TABLE IF NOT EXISTS PARTICIPANTES(
NUM_INSCRICAO INT,
CPF VARCHAR(14),
PRIMARY KEY(NUM_INSCRICAO,CPF),
NOME VARCHAR(100) NOT NULL,
DATA_NASC DATE NOT NULL,
EMPRESA VARCHAR(100));

ALTER TABLE PARTICIPANTES ADD EMAIL VARCHAR(30);
ALTER TABLE PARTICIPANTES DROP COLUMN EMAIL;

CREATE TABLE IF NOT EXISTS LOCAIS(
ID_LOCAL INT PRIMARY KEY,
NOME_LOCAL VARCHAR(100) NOT NULL,
LOG_LOCAL VARCHAR(100) NOT NULL,
LOG_NUM_LOCAL INT,
BAIRRO_LOCAL VARCHAR(50) NOT NULL,
CIDADE_LOCAL VARCHAR(50) NOT NULL,
UF_LOCAL CHAR(2) NOT NULL,
CEP_LOCAL VARCHAR(14) NOT NULL,
CAPACIDADE INT NOT NULL);

CREATE TABLE IF NOT EXISTS EVENTOS(
ID_EVENTO INT PRIMARY KEY,
NOME_EVENTO VARCHAR(100) NOT NULL,
DATA_EVENTO DATE NOT NULL,
ENTIDADE_EVENTO VARCHAR(100) NOT NULL,
LOCAL_EVENTO INT,
CONSTRAINT FK_LCL_EVT FOREIGN KEY(LOCAL_EVENTO) REFERENCES LOCAIS(ID_LOCAL));

CREATE TABLE IF NOT EXISTS ATIVIDADES(
ID_ATIVIDADE INT PRIMARY KEY,
NOME_ATV VARCHAR(100) NOT NULL,
DATA_ATV DATE NOT NULL,
HORA_ATV TIME NOT NULL,
EVENTO_ATV INT NOT NULL,
CONSTRAINT FK_EVT_ATV FOREIGN KEY(EVENTO_ATV) REFERENCES EVENTOS(ID_EVENTO));

CREATE TABLE IF NOT EXISTS PARTICIPANTES_EVENTOS(
PE_INSCRICAO INT,
PE_CPF VARCHAR(14),
PE_EVENTO INT,
PRIMARY KEY(PE_INSCRICAO,PE_CPF,PE_EVENTO),
CONSTRAINT FK_PE_PARTICIPANTES FOREIGN KEY(PE_INSCRICAO,PE_CPF) REFERENCES PARTICIPANTES(NUM_INSCRICAO,CPF),
CONSTRAINT FK_PE_EVENTOS FOREIGN KEY(PE_EVENTO) REFERENCES EVENTOS(ID_EVENTO));


CREATE TABLE IF NOT EXISTS PARTICIPANTES_ATIVIDADES(
PA_INSCRICAO INT,
PA_CPF VARCHAR(14),
PA_ATIVIDADE INT,
PRIMARY KEY(PA_INSCRICAO,PA_CPF,PA_ATIVIDADE),
CONSTRAINT FK_PA_PARTICIPANTES FOREIGN KEY(PA_INSCRICAO,PA_CPF) REFERENCES PARTICIPANTES(NUM_INSCRICAO,CPF),
CONSTRAINT FK_PA_ATIVIDADES FOREIGN KEY(PA_ATIVIDADE) REFERENCES ATIVIDADES(ID_ATIVIDADE));
