USE BDEX1_HOSPITAL;
# 1 - Quais são os pacientes agendados para consulta com um determinado médico, 
# incluindo informações do médico, em uma determinada data?
SELECT
CONSULTAS.DATA_CONS AS DATA,
CONSULTAS.HORA_CONS AS HORARIO,
PACIENTES.NOME AS PACIENTE,
MEDICOS.NOME AS MEDICO,
MEDICOS.CRM,
MEDICOS.UF,
DEPARTAMENTOS.NOME_ESPECIALIDADE AS ESPECIALIDADE
FROM CONSULTAS
JOIN MEDICOS
	ON CONSULTAS.CRM = MEDICOS.CRM AND CONSULTAS.UF = MEDICOS.UF
JOIN DEPARTAMENTOS
	ON MEDICOS.DEPTO_COD_ESPEC = DEPARTAMENTOS.COD_ESPECIALIDADE
JOIN PACIENTES
	ON PACIENTES.CPF_PACIENTE = CONSULTAS.CPF_PACIENTE
ORDER BY DATA,HORARIO;

# 2 - Quais são os médicos e seus respectivos departamentos, incluindo aqueles 
# que não estão associados a nenhum departamento?
SELECT
MEDICOS.NOME AS MEDICO,
DEPARTAMENTOS.NOME_ESPECIALIDADE AS DEPARTAMENTO
FROM MEDICOS LEFT JOIN DEPARTAMENTOS
ON MEDICOS.DEPTO_COD_ESPEC = DEPARTAMENTOS.COD_ESPECIALIDADE;

# 3 - Quais são os pacientes que já passaram por consulta com um determinado médico, 
#incluindo informações do médico, mesmo que não tenham sido atendidos?
SELECT
CONSULTAS.DATA_CONS AS DATA,
PACIENTES.NOME AS PACIENTE,
MEDICOS.NOME AS MEDICO,
MEDICOS.CRM,
MEDICOS.UF
FROM PACIENTES
JOIN CONSULTAS
	ON PACIENTES.CPF_PACIENTE = CONSULTAS.CPF_PACIENTE
JOIN MEDICOS
	ON CONSULTAS.CRM = MEDICOS.CRM AND CONSULTAS.UF = MEDICOS.UF
WHERE CONSULTAS.DATA_CONS < CURDATE() AND CONSULTAS.ANAMNESE IS NULL;

USE BDEX2_PASSAGENS_AEREAS;
#1 - Quais são os voos disponíveis de um determinado aeroporto para outro em uma 
# determinada data, incluindo informações dos aeroportos de partida e chegada?
SELECT
DATA_PART AS DATA_EMBARQUE,
HORA_PART AS HORA_EMBARQUE,
CIA_AEREAS.NOME_FANTASIA AS OPERADORA,
PART.NOME AS EMBARQUE,
CHEG.NOME AS DESTINO,
DATA_CHEG AS DATA_PREVISTA,
HORA_CHEG AS HORARIO_PREVISTO
FROM VOOS
JOIN AEROPORTOS AS PART ON PART.ID_AEROPORTO = VOOS.AERO_PART
JOIN AEROPORTOS AS CHEG ON CHEG.ID_AEROPORTO = VOOS.AERO_CHEG
JOIN CIA_AEREAS ON CIA_AEREAS.ID_CIA = VOOS.CIA_AEREA;
#2 - Quais são os passageiros reservados em um determinado voo,
#incluindo aqueles que ainda não reservaram?
SELECT
CONCAT(P.NOME,' ', P.SOBRENOME) PASSAGEIRO,
V.DATA_PART AS DATA_EMBARQUE,
V.HORA_PART AS HORA_EMBARQUE,
CA.NOME_FANTASIA AS OPERADORA,
A.NOME AS EMBARQUE
FROM PASSAGEIROS P
LEFT JOIN PASSAGEIROS_RESERVAS PR ON PR.PASSAGEIRO = P.COD_PASSAGEIRO
LEFT JOIN VOOS_RESERVAS VR ON VR.ID_RESERVA = PR.ID_RESERVA
LEFT JOIN VOOS V ON V.ID_VOO = VR.ID_VOO
LEFT JOIN AEROPORTOS A ON A.ID_AEROPORTO = V.AERO_PART
LEFT JOIN CIA_AEREAS CA ON CA.ID_CIA = V.CIA_AEREA;

#3 - Quais são os voos operados por uma determinada companhia aérea, 
# incluindo aquelas que não têm operações?
SELECT 
CA.NOME_FANTASIA AS OPERADORA,
A.NOME AS EMBARQUE,
V.DATA_PART AS DATA_EMBARQUE,
V.HORA_PART AS HORA_EMBARQUE
FROM CIA_AEREAS AS CA
LEFT JOIN VOOS V ON CA.ID_CIA = V.CIA_AEREA 
LEFT JOIN AEROPORTOS A ON A.ID_AEROPORTO = V.AERO_PART;


