-- Comandos DELETE para a tabela PARTICIPANTES
DELETE FROM PARTICIPANTES WHERE NUM_INSCRICAO = 1;
DELETE FROM PARTICIPANTES WHERE CPF = '234.567.890-12';

-- Comandos DELETE para a tabela LOCAIS
DELETE FROM LOCAIS WHERE ID_LOCAL = 1;
DELETE FROM LOCAIS WHERE CIDADE = 'Recife';

-- Comandos DELETE para a tabela EVENTOS
DELETE FROM EVENTOS WHERE ID_EVENTO = 1;
DELETE FROM EVENTOS WHERE NOME_EVENTO = 'Expo de Dispositivos';

-- Comandos DELETE para a tabela ATIVIDADES
DELETE FROM ATIVIDADES WHERE ID_ATIVIDADE = 1;
DELETE FROM ATIVIDADES WHERE NOME_ATV = 'Workshop de Fotografia';

-- Comandos DELETE para a tabela PARTICIPANTE_EVENTO
DELETE FROM PARTICIPANTE_EVENTO WHERE INSCRICAO = 1;
DELETE FROM PARTICIPANTE_EVENTO WHERE EVENTO = 10;

-- Comandos DELETE para a tabela PARTICIPANTE_ATIVIDADE
DELETE FROM PARTICIPANTE_ATIVIDADE WHERE CPF = '123.456.789-01';
DELETE FROM PARTICIPANTE_ATIVIDADE WHERE ATIVIDADE = 10;
