USE BDEX4_ESTOQUE;

UPDATE PRODUTOS SET PRECO = 15.00 WHERE ID_PRODUTO = 1;
UPDATE PRODUTOS SET DESCRICAO = 'Nova descrição' WHERE ID_PRODUTO = 2;

UPDATE FORNECEDORES SET NOME = 'Novo Nome' WHERE ID_FORNECEDOR = 1;
UPDATE FORNECEDORES SET CNPJ = '99999999999999' WHERE ID_FORNECEDOR = 2;

UPDATE ARMAZENS SET CIDADE_ARMAZEM = 'Nova Cidade' WHERE ID_ARMAZEM = 1;
UPDATE ARMAZENS SET UF_ARMAZEM = 'ZZ' WHERE ID_ARMAZEM = 2;

UPDATE PEDIDOS_COMPRA SET DATA_PEDIDO = '2024-05-10' WHERE ID_PEDIDO = 1;
UPDATE PEDIDOS_COMPRA SET HORA_PEDIDO = '14:30:00' WHERE ID_PEDIDO = 2;

UPDATE PRODUTOS_FORNECEDORES SET PRODUTO = 3 WHERE FORNECEDOR = 1;
UPDATE PRODUTOS_FORNECEDORES SET FORNECEDOR = 4 WHERE PRODUTO = 2;

SET FOREIGN_KEY_CHECKS = 0; #USADO APENAS PARA FINS DE APRENDIZADO - LIBERA AS RESTRIÇÕES DE CHAVE ESTRANGEIRA

DELETE FROM PRODUTOS WHERE ID_PRODUTO = 3;
DELETE FROM PRODUTOS WHERE ID_PRODUTO = 4;

DELETE FROM FORNECEDORES WHERE ID_FORNECEDOR = 3;
DELETE FROM FORNECEDORES WHERE ID_FORNECEDOR = 4;

DELETE FROM ARMAZENS WHERE ID_ARMAZEM = 3;
DELETE FROM ARMAZENS WHERE ID_ARMAZEM = 4;

DELETE FROM PEDIDOS_COMPRA WHERE ID_PEDIDO = 3;
DELETE FROM PEDIDOS_COMPRA WHERE ID_PEDIDO = 4;

DELETE FROM PRODUTOS_FORNECEDORES WHERE PRODUTO = 1;
DELETE FROM PRODUTOS_FORNECEDORES WHERE FORNECEDOR = 5;

