USE BDEX3_REDESOCIAL;

UPDATE USUARIOS SET NOME_USUARIO = 'João Silva' WHERE ID_USUARIO = 1;
UPDATE USUARIOS SET SOBRENOME = 'Santana' WHERE ID_USUARIO = 2;

UPDATE GRUPOS SET NOME_GRUPO = 'Amigos Próximos' WHERE ID_GRUPO = 1;
UPDATE GRUPOS SET DESCRICAO = 'Grupo de colegas de trabalho próximos' WHERE ID_GRUPO = 2;

UPDATE POSTAGENS SET TEXTO = 'Nova postagem!' WHERE ID_POST = 1;
UPDATE POSTAGENS SET DATA_HORA = '2024-05-01 12:00:00' WHERE ID_POST = 2;

UPDATE COMENTARIOS SET TEXTO = 'Bela foto!' WHERE ID_COMENTARIO = 1;
UPDATE COMENTARIOS SET DATAHORA = '2024-05-02 10:00:00' WHERE ID_COMENTARIO = 2;

UPDATE SEGUIDORES_USUARIOS SET SEGUIDOR = 3 WHERE USUARIO = 1;
UPDATE SEGUIDORES_USUARIOS SET USUARIO = 4 WHERE SEGUIDOR = 1;

UPDATE USUARIOS_GRUPOS SET GRUPO = 3 WHERE USUARIO = 1;
UPDATE USUARIOS_GRUPOS SET USUARIO = 2 WHERE GRUPO = 1;

SET FOREIGN_KEY_CHECKS = 0; #USADO APENAS PARA FINS DE APRENDIZADO - LIBERA AS RESTRIÇÕES DE CHAVE ESTRANGEIRA

DELETE FROM USUARIOS WHERE ID_USUARIO = 3;
DELETE FROM USUARIOS WHERE ID_USUARIO = 4;

DELETE FROM GRUPOS WHERE ID_GRUPO = 3;
DELETE FROM GRUPOS WHERE ID_GRUPO = 4;

DELETE FROM POSTAGENS WHERE ID_POST = 3;
DELETE FROM POSTAGENS WHERE ID_POST = 4;

DELETE FROM COMENTARIOS WHERE ID_COMENTARIO = 3;
DELETE FROM COMENTARIOS WHERE ID_COMENTARIO = 4;

DELETE FROM SEGUIDORES_USUARIOS WHERE USUARIO = 3;
DELETE FROM SEGUIDORES_USUARIOS WHERE SEGUIDOR = 4;

DELETE FROM USUARIOS_GRUPOS WHERE USUARIO = 3;
DELETE FROM USUARIOS_GRUPOS WHERE GRUPO = 2;
