USE BDEX1_HOSPITAL;

#COMANDOS DE UPDATE
UPDATE PACIENTES SET TELEFONE = '(12) 3333-3333' WHERE CPF_PACIENTE = '12345678900';
UPDATE PACIENTES SET EMAIL = 'ana.souza@novoemail.com' WHERE CPF_PACIENTE = '11122233344';

UPDATE DEPARTAMENTOS SET NOME_ESPECIALIDADE = 'Clínica Médica' WHERE COD_ESPECIALIDADE = 1;
UPDATE DEPARTAMENTOS SET NOME_ESPECIALIDADE = 'Oftalmologista' WHERE COD_ESPECIALIDADE = 3;

UPDATE MEDICOS SET EMAIL = 'beatriz.santos@novomedico.com' WHERE CRM = 54321 AND UF = 'RJ';
UPDATE MEDICOS SET DEPTO_COD_ESPEC = 4 WHERE CRM = 98765;

UPDATE CONSULTAS SET HORA_CONS = '10:30:00' WHERE ID_CONSULTA = 1;
UPDATE CONSULTAS SET ANAMNESE = 'Paciente refere dor abdominal intensa' WHERE ID_CONSULTA = 3;

#COMANDO DE DELETE

SET FOREIGN_KEY_CHECKS = 0; #USADO APENAS PARA FINS DE APRENDIZADO - LIBERA AS RESTRIÇÕES DE CHAVE ESTRANGEIRA

DELETE FROM PACIENTES WHERE CPF_PACIENTE = '00012345678';
DELETE FROM PACIENTES WHERE CPF_PACIENTE = '22233344455';

DELETE FROM DEPARTAMENTOS WHERE COD_ESPECIALIDADE = 2;
DELETE FROM DEPARTAMENTOS WHERE COD_ESPECIALIDADE = 4;

DELETE FROM CONSULTAS WHERE ID_CONSULTA = 2;
DELETE FROM CONSULTAS WHERE ID_CONSULTA = 4;

DELETE FROM MEDICOS WHERE CRM = 12345 AND UF = 'SP';
DELETE FROM MEDICOS WHERE CRM = 98765;


