USE BDEX2_PASSAGENS_AEREAS;

UPDATE PASSAGEIROS SET NACIONALIDADE = 'Mexicano' WHERE COD_PASSAGEIRO = 1;
UPDATE PASSAGEIROS SET SOBRENOME = 'Alves' WHERE COD_PASSAGEIRO = 2;

UPDATE AEROPORTOS SET CIDADE = 'Abu Dhabi' WHERE ID_AEROPORTO = 1;
UPDATE AEROPORTOS SET PAIS = 'Japão' WHERE ID_AEROPORTO = 2;

UPDATE CIA_AEREAS SET NOME_FANTASIA = 'United Airlines' WHERE ID_CIA = 1;
UPDATE CIA_AEREAS SET CNPJ = '98765432109877' WHERE ID_CIA = 2;

UPDATE RESERVAS SET FORMA_PGTO = 'DEBITO' WHERE ID_RESERVA = 1;
UPDATE RESERVAS SET VALOR_RESERVA = 600.00 WHERE ID_RESERVA = 2;

UPDATE AERONAVES SET POLTRONAS = 200 WHERE PFX_AERO = 'ABC123';
UPDATE AERONAVES SET FABRICANTE = 'Boeing' WHERE PFX_AERO = 'DEF456';

UPDATE VOOS SET DATA_PART = '2024-05-15' WHERE ID_VOO = 1;
UPDATE VOOS SET HORA_PART = '09:30:00' WHERE ID_VOO = 2;

UPDATE VOOS_RESERVAS SET ASSENTO = 'F6' WHERE ID_VOO = 1 AND ID_RESERVA = 1;
UPDATE VOOS_RESERVAS SET ID_RESERVA = 3 WHERE ID_VOO = 2 AND ID_RESERVA = 2;

UPDATE PASSAGEIROS_RESERVAS SET PASSAGEIRO = 3 WHERE PASSAGEIRO = 2 AND ID_RESERVA = 2;
UPDATE PASSAGEIROS_RESERVAS SET ID_RESERVA = 1 WHERE PASSAGEIRO = 3 AND ID_RESERVA = 3;

SET FOREIGN_KEY_CHECKS = 0; #USADO APENAS PARA FINS DE APRENDIZADO - LIBERA AS RESTRIÇÕES DE CHAVE ESTRANGEIRA

DELETE FROM PASSAGEIROS WHERE COD_PASSAGEIRO = 1;
DELETE FROM PASSAGEIROS WHERE COD_PASSAGEIRO = 2;

DELETE FROM AEROPORTOS WHERE ID_AEROPORTO = 1;
DELETE FROM AEROPORTOS WHERE ID_AEROPORTO = 2;

DELETE FROM CIA_AEREAS WHERE ID_CIA = 1;
DELETE FROM CIA_AEREAS WHERE ID_CIA = 2;

DELETE FROM RESERVAS WHERE ID_RESERVA = 1;
DELETE FROM RESERVAS WHERE ID_RESERVA = 2;

DELETE FROM AERONAVES WHERE PFX_AERO = 'ABC123';
DELETE FROM AERONAVES WHERE PFX_AERO = 'DEF456';

DELETE FROM VOOS WHERE ID_VOO = 1;
DELETE FROM VOOS WHERE ID_VOO = 2;

DELETE FROM VOOS_RESERVAS WHERE ID_VOO = 1 AND ID_RESERVA = 1;
DELETE FROM VOOS_RESERVAS WHERE ID_VOO = 2 AND ID_RESERVA = 2;

DELETE FROM PASSAGEIROS_RESERVAS WHERE PASSAGEIRO = 3 AND ID_RESERVA = 2;
DELETE FROM PASSAGEIROS_RESERVAS WHERE PASSAGEIRO = 3 AND ID_RESERVA = 3;
