-- Exclusão na tabela USUARIOS
DELETE FROM USUARIOS
WHERE ID_USER = 3;

DELETE FROM USUARIOS
WHERE ID_USER = 4;

-- Exclusão na tabela CONTAS
DELETE FROM CONTAS
WHERE COD_BANCO = 5;

DELETE FROM CONTAS
WHERE COD_BANCO = 6;

-- Exclusão na tabela TRANSACOES
DELETE FROM TRANSACOES
WHERE ID_TRANS = 7;

DELETE FROM TRANSACOES
WHERE ID_TRANS = 8;

-- Exclusão na tabela SALDOS
DELETE FROM SALDOS
WHERE ID_SALDO = 9;

DELETE FROM SALDOS
WHERE ID_SALDO = 10;
